// @ts-ignore
import { pxPair, pxToRemPair } from '@captaincss/captaincss/helpers'

export const spacing = {
  px: '1px',
  ...pxPair(0),
  ...pxToRemPair(0.5),
  ...pxToRemPair(1),
  ...pxToRemPair(1.5),
  ...pxToRemPair(2),
  ...pxToRemPair(2.25),
  ...pxToRemPair(2.5),
  ...pxToRemPair(3),
  ...pxToRemPair(3.5),
  ...pxToRemPair(4),
  ...pxToRemPair(5),
  ...pxToRemPair(6),
  ...pxToRemPair(7),
  ...pxToRemPair(8),
  ...pxToRemPair(9),
  ...pxToRemPair(10),
  ...pxToRemPair(11),
  ...pxToRemPair(12),
  ...pxToRemPair(14),
  ...pxToRemPair(16),
  ...pxToRemPair(18),
  ...pxToRemPair(20),
  ...pxToRemPair(22),
  ...pxToRemPair(24),
  ...pxToRemPair(26),
  ...pxToRemPair(28),
  ...pxToRemPair(30),
  ...pxToRemPair(32),
  ...pxToRemPair(36),
  ...pxToRemPair(40),
  ...pxToRemPair(44),
  ...pxToRemPair(48),
  ...pxToRemPair(52),
  ...pxToRemPair(56),
  ...pxToRemPair(60),
  ...pxToRemPair(64),
  ...pxToRemPair(68),
  ...pxToRemPair(72),
  ...pxToRemPair(80),
  ...pxToRemPair(96),
  ...pxToRemPair(120),
};
