version: 2
updates:
  # Fetch and update latest `composer` packages
  - package-ecosystem: composer
    directory: '/'
    schedule:
      interval: weekly
      day: tuesday
      time: '11:00'
    open-pull-requests-limit: 15
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope

  # Fetch and update latest `github-actions` pkgs
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: weekly
      day: tuesday
      time: '11:00'
    open-pull-requests-limit: 10
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope

