version: 2
updates:
  # Fetch and update latest `pnpm` packages for project root
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: weekly
      day: thursday
      time: '14:00'
    open-pull-requests-limit: 15
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope

  # Fetch and update latest `github-actions` packages for project root
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: weekly
      day: thursday
      time: '14:00'
    open-pull-requests-limit: 10
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope

  # Fetch and update latest project `pnpm` packages for /src directory
  - package-ecosystem: npm
    directory: '/src/'
    schedule:
      interval: weekly
      day: thursday
      time: '14:00'
    open-pull-requests-limit: 15
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope
